const http = require('http');
const fs = require("fs").promises; // Use fs with promises
const PORT = 2001;

const server = http.createServer(async (request, response) => {
    if (request.url === "/" && request.method === "GET") {
        response.setHeader('Content-Type', 'text/html');
        response.write(`<h2 style="color:blue;">Data is being generated by server</h2>`);
        response.end("<h2 style='color:red;'>Welcome to Node Server</h2>");
    }
    else if (request.url === "/data" && request.method === "GET") {
        response.setHeader("Content-Type", "text/html"); 

        const data = await fs.readFile("student.json", "utf8");
        const htmldata = `<h2 style="color:red;">${data}</h2>`
        response.end(htmldata);
    }
    else if (request.url === "/data" && request.method === "POST") {
        response.setHeader("Content-Type", "application/json");
        response.end(JSON.stringify({ message: "Data inserted successfully" }));
    }
    else if (request.url === "/data" && request.method === "PUT") {
        response.setHeader("Content-Type", "application/json");
        const obj = { message: "Data is updated successfully" };  
        response.end(JSON.stringify(obj)); 
    }
});

server.listen(PORT, () => {
    console.log("Server is running on port " + PORT);
});
